name: Syft SBOM + Grype vuln scan

on:
  push:
    tags: ["v*"]
  pull_request:

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Generate SBOM (always)
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-source.spdx.json
          upload-artifact: true
          artifact-name: sbom-artifact
          upload-release-assets: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

  vuln-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Scan with grype
        id: scan
        uses: anchore/scan-action@v6
        with:
          path: .
          output-format: table
          fail-build: false
          cache-db: true
