name: Syft SBOM

on:
  push:
    tags: [ "v*" ]
  pull_request:
  
permissions:
  contents: write
  actions: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Generate SBOM (non-tag)
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-source.spdx.json
          upload-artifact: false
          upload-release-assets: false

      - name: Generate SBOM (tag) & attach to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-source.spdx.json
          artifact-name: sbom-source.spdx.json
          upload-artifact: true
          upload-release-asset: true

      - name: Upload SBOM artifact (non-tag)
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: actions/upload-artifact@v4
        with:
          name: sbom-source.spdx.json
          path: sbom-source.spdx.json
          if-no-files-found: error
